-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 03:43:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema store_website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store_website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store_website` DEFAULT CHARACTER SET utf8 ;
USE `store_website` ;

-- -----------------------------------------------------
-- Table `store_website`.`product_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_website`.`product_info` (
  `productID` INT(11) NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(45) NOT NULL,
  `productPrice` FLOAT NOT NULL,
  `productQuantity` INT(11) NOT NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_website`.`user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_website`.`user_address` (
  `addressID` INT(11) NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zipcode` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`addressID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_website`.`user_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_website`.`user_login` (
  `loginID` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`loginID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_website`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_website`.`user_info` (
  `memberID` INT(11) NOT NULL AUTO_INCREMENT,
  `addressID` INT(11) NOT NULL,
  `loginID` INT(11) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(10) NOT NULL,
  `isModerator` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`memberID`),
  INDEX `fk_addressID_idx` (`addressID` ASC) VISIBLE,
  INDEX `fk_loginID_idx` (`loginID` ASC) VISIBLE,
  CONSTRAINT `fk_addressID`
    FOREIGN KEY (`addressID`)
    REFERENCES `store_website`.`user_address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loginID`
    FOREIGN KEY (`loginID`)
    REFERENCES `store_website`.`user_login` (`loginID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
